name: 'Build'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build_linux_x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: libgtk-3-dev libgtk-3-common libgtk-3-bin build-essential git cmake ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libevdev-dev libusb-1.0-0-dev libxrandr-dev libxi-dev libpangocairo-1.0-0 qt6-base-private-dev libqt6svg6-dev libbluetooth-dev libasound2-dev libpulse-dev libgl1-mesa-dev libcurl4-openssl-dev
          
      - name: Build Linux x64
        run: |
          sudo apt-get install libudev-dev libsystemd-dev || sudo apt-get install libeudev-dev
          mkdir build && cd build
          cmake .. -DLINUX_LOCAL_DEV=true
          make -j$(nproc)
          ln -s ../../Data/Sys Binaries/
          tar -czf Linux_x64.tar.gz "Binaries"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux_x64.tar.gz
          path: Linux_x64.tar.gz

  build_windows_x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
         
      - name: Build
        run: |
          cd Source
          msbuild /p:Configuration=Release /p:Platform=x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows_x64
          path: Binaries
          
